### ISSUE TITLE
How do you change the environmental variables? Where is the file that you change?

### ISSUE THREAD

**Issue by Cindy-Jie-01** [owulveryck/goMarkableStream#16]

**Comment by owulveryck** [comment]
I should add this information to the README.
Thanks

**Comment by owulveryck** [comment]
I know how to do it on Linux and Mac but I need to look how to do it easily in windows. 
I think that you can use setx in a cmd prompt.
For example 

`setx RK_CLIENT_COLORIZE “true”`
Then run
`goMarkableClient.exe`

Or maybe create a `.bat` file

This may help you:

https://superuser.com/questions/1049430/how-do-you-set-environment-variables-for-a-single-command-on-windows

Can I ask you to share how you did it when you succeed (or open a PR if you are comfortable with it)

**Comment by Cindy-Jie-01** [comment]
I couldn't get it to work with set in the cmd prompt. I'm not sure how to use .bat files :(

**Comment by owulveryck** [comment]
I tried to upload this: https://raw.githubusercontent.com/owulveryck/goMarkableStream/windows/misc/windows/client.bat
can you try to download it in the same directory where the client is and launch it? 
Thanks for your help

**Comment by Cindy-Jie-01** [comment]
I keep getting this now no matter how I close and restart files (tried all the possible orders)
reMarkable: ~/ './goMarkableStreamServer.arm'
2021/05/23 18:29:51 listening on tcp :2000
2021/05/23 18:29:51 listen tcp :2000: bind: address already in use

**Comment by owulveryck** [comment]
This means that the server is already running.
Therefore you don't need to restart it.

**Comment by owulveryck** [comment]
If you want to kill it anyway, so you can restart it properly you can use:

`kill $(pidof goMarkableStreamServer.arm)`

**Comment by owulveryck** [comment]
One more thing, you may need to specify the `RK_SERVER_ADDR` in the. "bat" file.

**Comment by Cindy-Jie-01** [comment]
it's still not quite working
![image](https://user-images.githubusercontent.com/65687259/119386333-61175480-bc95-11eb-91cf-ca49352587e4.png)
![image](https://user-images.githubusercontent.com/65687259/119386345-65437200-bc95-11eb-88f2-c59e67a3cd19.png)

**Comment by owulveryck** [comment]
I think I know what is wrong: you should not add `root@` in the server address, simply `10.11.99.1:2000`

**Comment by Cindy-Jie-01** [comment]
yes it works now! for the colorizing turn on, it seems to recognize any lighter grey as highlighter even in pdf
![image](https://user-images.githubusercontent.com/65687259/119390146-a1c59c80-bc9a-11eb-95a1-d8f1ec249882.png)
also it seems that even with autorotate on, it wont autorotate even after reload

**Comment by owulveryck** [comment]
Cool!

I see that you have the hack from ddvk installed.
This is the reason why the auto rotation is not working.
It tries to locate the toggle on the screen which is different when the hack is on.
I do not install the hack, therefore I did not implement this. If I got time, I will use it.
Or, if you are willing to help, you can send me 4 raw pictures (that you can grab by calling `/raw`)

Each page should be blank with the toggle only.
- one portrait right-hand 
- one landscape right-hand
- one portrait left-hand
- one landscape left-hand

Regarding the colorize feature, it is not bullet proof yet. It is understandable that it detect light gray as yellow because it is how it should work, but I may tweak it a little bit to be less restrictive in a future release.

I hope you’ll enjoy the tool, and thank you for your feedback.

PS: does the batch file work?
