### ISSUE TITLE
Process name

### ISSUE THREAD

**Issue by GregTheGreek** [owulveryck/goMarkableStream#35]
After the remarkable goes to sleep Im finding the process gets a bit funky, and i can't connect to it. 

ps aux doens't seem to work within the remarkable, any idea what the process might be for me to kill it manually?

**Comment by owulveryck** [comment]
I usually launch the process with a nohup, and I have no problem connecting to it after a sleep period.
There is also a systemctl script you can install that will launch it and monitor it, but as it disappear after an update I did not document it. Besides, there is an ugly sleep in this script that slows the startup of the device (an issue it opened to fix this)
I think that a pkill command could do the trick as well.

I cannot tell you more right now because I do not have the device with me this week.

Hope it helps anyway.

**Comment by GregTheGreek** [comment]
Thanks I ended up clearing up my issues witha restart! Also happened to use the wrong IP haha. This tool works amazingly well!

**Comment by 2Belette** [comment]
@owulveryck thanks for the project ! 
I added this systemd unit : 
```
goMarkableStream.service 
[Unit]
Description=goMarkableStream
Requires=xochitl.service
After=xochitl.service network.target

[Service]
Environment="RK_SERVER_BIND_ADDR=:443" "RK_SERVER_USERNAME=xxx" "RK_SERVER_PASSWORD=xxx"
ExecStart=/home/root/goMarkableStream
ExecStartPre=/bin/sleep 30
Restart=always

[Install]
WantedBy=multi-user.target
```
It is all working fine at boot, when the tablet is in light sleep, for a couple of minutes it is fine, but after that when I unlock the tablet, I got this : 

![2023 08 21 09 51 07](https://github.com/owulveryck/goMarkableStream/assets/2325706/c64715c8-fb64-48b5-b99d-12711989eb3d)

I know the connectivity is all fine (I am in ssh in //), refreshing is not solving, restarting the service is doing the trick.

Any idea?

**Comment by 2Belette** [comment]
Seems to be solved with this [version](https://github.com/owulveryck/goMarkableStream/issues/76#issuecomment-1778052464) of the systemd unit
