### ISSUE TITLE
Black screen in the browser

### ISSUE THREAD

**Issue by freshteapot** [owulveryck/goMarkableStream#36]
> Connects without complaints.

It used to work perfectly.
But it seems to have stopped working with 3.X version.
I am pretty sure it worked until very recent upgrades.

I have explored the getPointer function but to no joy.

Reading #23 was a joy to learn how to do it without code.

Even tho it didn't work, when I put the hex in from getPointer, it at least didn't complain.

**Comment by freshteapot** [comment]
I take it back.
It is a black overlay.

This pdf was made via
```sh
cat ~/Downloads/gob | convert -depth 8 -size 1404x1872+0 gray:- shot.pdf
```

[shot.pdf](https://github.com/owulveryck/goMarkableStream/files/11262499/shot.pdf)

**Comment by owulveryck** [comment]
It looks like they have changed the format of the picture.
My first guess it that the `getPointer` is ok, but the number of bytes we need to extract and the raw format needs to be changed.

**Comment by thatInfrastructureGuy** [comment]
Facing the same issue. Additionally, the Linux commands listed in the [blog post](https://blog.owulveryck.info/2021/03/30/streaming-the-remarkable-2.html) too are not working for me.

**Comment by owulveryck** [comment]
I am on it, but time is missing.
I will do my very best to fix it.

**Comment by freshteapot** [comment]
I would love to learn how you solve it, so I can help with the next PR.

**Comment by owulveryck** [comment]
What I've done so far is extract a memory image from the process with `dd` and try to locate an image within it.

- find the memory space of the virtual framebuffer with `cat /proc/$(pidof xochitl)/maps` (the memory space is located right after the /dev/fb0 definition)
- extract a picture, for example: `dd if=/proc/$(pidof xochitl)/mem of=test.raw count=7884864 bs=1 skip=$((0x763a2004))` if `0x763a2004` is the address you've found
- play with the test.raw to find a picture in it (imagemagick is you friend): for example: `convert -depth 8 -size 1404x1872+0 rgb:test.raw test.png ` tries to convert the image in PBG assuming 8 bits pictures in rgb.

The knowledge we have so far is:
- the screen resolution that is 1404x1872 (and normally, the size of the raw file we extract should be a multiple of 1404x1872 because there is no header of any kind as is it a raw picture).

Once we figure out the image format, tweaking the go code should be fairly straightforward.

I hope it helps...

**Comment by owulveryck** [comment]
Just in case, there is this article that describes a bit how things works: https://blog.owulveryck.info/2021/03/30/streaming-the-remarkable-2.html

**Comment by mbursa** [comment]
I am not sure if that helps, but I am running into the same or a similar issue using remarkable2 firmware 3.3 and the latest goRemarkableStream (0.6.4). What I see in the browser looks like the page having an almost black overlay: [screenshot](https://ibb.co/jRcvVpb), however you can still see the actual content.

Adjusting levels with
```
$ convert screenshot.png -level 0%,5% screenshot_adjusted.png
```
will produce a perfect result.

**Comment by owulveryck** [comment]
It helps a lot, thank you.
With that in mind, a fix should be fairly easy to implement.
I will look at it hopefully today.

**Comment by freshteapot** [comment]
Confirming it works great on reMarkable 3.4 software.

(sorry for the delay)

And very nice work on streaming to canvas.
