### ISSUE TITLE
Rotation available in 0.8.5?

### ISSUE THREAD

**Issue by jimbolaya** [owulveryck/goMarkableStream#71]
I'm still running 2.15 firmware on my reMarkable, so from the documentation here it shows I should use 0.8.5 (or less).

The screen on my web page is landscape, so I was looking around for rotation things.

I was looking at https://github.com/owulveryck/goMarkableStream/pull/31 and tried going to

https://remarkable:2001/orientation?orientation=portrait

but it doesn't seem to make a difference.

So I'm wondering if this change made it to 0.8.5. Also, I don't see a rotate button that seemed to be added in 0.8.2.

I have koreader, so that might be affecting things.

**Comment by loughnane** [comment]
Wonderful project. Super sleek.

I'm having the same issue, though I"m on a pretty vanilla remarkable install, have only configured some things for rmfakecloud.

Any easy fixes, or would i have to update the firmware to get rotation?

**Comment by owulveryck** [comment]
Hello, 

As mentioned in another comment, I develop the tool mainly for my own usage and therefore I don't have time or material to maintain several versions and backport the new features.

Beside this, I am surprised because orientation was supposed to work on all versions (it is a mandatory feature for me).

I cannot test is myself but the `https://remarkable:2001/orientation?orientation=portrait` should work. There was also an auto rotation mechanism in the old versions, but only work without the hack (it was analysing the toggle menu on the picture, and the dddvk hacks were moving it a bit)

**Comment by jimbolaya** [comment]
Ah, I understand now. The menu is hidden. You have to move the mouse to the left side of the browser window. 

I apologize, I didn't understand that before.
